apiVersion: v1
kind: Service
metadata:
  name: nginx-service-flux
  namespace: nginx-app-namespace
  labels:
    name: nginx-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodeport: 30994
  selector:
    name: nginx-app-deployment
