---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-nginx-application
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/rajesh17mca/flux-nginx-application.git
