---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-nginx-application
  namespace: flux-system
spec:
  interval: 30s
  path: ./nginx-app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-nginx-application
  validate: false
